<a href="https://colab.research.google.com/github/jorgg3/Proyecto-2/blob/main/Ejercicio19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 2: Solución a Sistemas de Ecuaciones Lineales
**Problemas Computacionales**\
Alumno: Martínez de la Cruz José Jorge\
Profesor: César Carreón Otañez\
Ayudante:  Jesús Iván Coss Calderón

*** NOTAS: Todos los códigos fueron comentados por ChatGPT, incluso los códigos vistos en clase (ayudantía), todas las modificaciones a dichos códigos fueron creación propia.***

In [68]:
#Cargamos la factorización LU:
import numpy as np

def FactLU(A):
    """
    Realiza la factorización LU de una matriz cuadrada A, descomponiéndola en el producto de
    una matriz triangular inferior L y una matriz triangular superior U, tales que A = LU.

    Parámetros:
    A (numpy.ndarray): La matriz cuadrada que se desea factorizar.

    Retorna:
    tuple: Una tupla (L, U), donde:
        - L (numpy.ndarray): Matriz triangular inferior.
        - U (numpy.ndarray): Matriz triangular superior.
    """
    U = np.copy(A)  # Copia la matriz A para trabajar en U sin modificar A directamente
    n = A.shape[1]  # Número de columnas (y filas, ya que es cuadrada)
    L = np.eye(n)  # Inicializa L como la matriz identidad de tamaño n

    # Realiza iteración sobre las columnas para la construcción de L y U
    for j in range(n):
        Lj = np.eye(n)  # Matriz identidad que actuará como transformadora en cada paso
        for i in range(j + 1, n):
            Lj[i, j] = -U[i, j] / U[j, j]  # Calcula el multiplicador para hacer ceros en U
        L = L @ Lj  # Acumula el producto de matrices transformadoras en L
        U = Lj @ U  # Aplica la transformación en U para hacer ceros debajo del pivote actual

    # Ajusta L para obtener la matriz triangular inferior correcta
    L = 2 * np.eye(n) - L

    return L, U  # Retorna las matrices L y U resultantes

In [5]:
def SustDelante(L,b):
  x=np.zeros_like(b)
  n=L.shape[0]# cantidad de renglones de L
  for i in range(n):
    sum=0.0
    for j in range(i):
      sum+=L[i,j]*x[j]
    x[i]=(b[i]-sum)/L[i,i]

  return x

In [6]:
def SustAtras(U,y):
  x=np.zeros_like(y)
  n=U.shape[0]# cantidad de renglones de U
  x[n-1]=y[n-1]/U[n-1][n-1]

  for i in range(n-2,-1,-1):
    sum=0.0
    for j in range(i+1,n):
      sum+=U[i,j]*x[j]
    x[i]=(y[i]-sum)/U[i,i]

  return x

In [7]:
def SolverLU(A,b):
  L,U=FactLU(A)
  y=SustDelante(L,b)
  x=SustAtras(U,y)

  return x

19) Dados $A$ y $b$ como sigue, resolver con factorización LU, factorización LU con pivoteo parcial y factorización LU con pivoteo total

# Factorización LU

$$
A = \begin{bmatrix}
  4 & -1 & 3 \\
  -8 & 4 & -7 \\
  12 & 1 & 8 \\
\end{bmatrix},
b =\begin{bmatrix}
  -8\\
  19\\
  -19\\
\end{bmatrix}
$$

In [8]:
A = np.array([[4, -1, 3], [-8, 4, -7], [12, 1, 8]])
b = np.array([-8, 19, -19])
print(A)
print(b)

[[ 4 -1  3]
 [-8  4 -7]
 [12  1  8]]
[ -8  19 -19]


In [9]:
SolverLU(A, b)

array([-1,  1, -1])

La solución es el vector $(-1, 1, -1)$

$$
A = \begin{bmatrix}
  1 & 4 & -2 & 1 \\
  -2 & -4 & -3 & 1 \\
  1 & 16 & -17 & 9 \\
  2 & 4 & -9 & -3
\end{bmatrix},
b =\begin{bmatrix}
  3.5\\
  -2.5\\
  15\\
  10.5
\end{bmatrix}
$$

In [10]:
A = np.array([[1, 4, -2, 1], [-2, -4, -3, 1], [1, 16, -17, 9], [2, 4, -9, -3]])
b = np.array([3.5, -2.5, 15, 10.5])
print(A)
print(b)

[[  1   4  -2   1]
 [ -2  -4  -3   1]
 [  1  16 -17   9]
 [  2   4  -9  -3]]
[ 3.5 -2.5 15.  10.5]


In [11]:
SolverLU(A, b)

array([-0.5,  1. , -0.5, -1. ])

La solución es el vector $(-0.5, 1, -0.5, -1)$

$$
A = \begin{bmatrix}
  4 & 5 & -1 & 2 & 3 \\
  12 & 13 & 0 & 10 & 3 \\
  -8 & -8 & 5 & -11 & 4 \\
  16 & 18 & -7 & 20 & 4 \\
  -4 & -9 & 31 & -31 & -1
\end{bmatrix},
b =\begin{bmatrix}
  34\\
  93\\
  -33\\
  131\\
  -58
\end{bmatrix}
$$

In [12]:
A = np.array([[4, 5, -1, 2, 3], [12, 13, 0, 10, 3], [-8, -8, 5, -11, 4], [16, 18, -7, 20, 4], [-4, -9, 31, -31, -1]])
b = np.array([34, 93, -33, 131, -58])
print(A)
print(b)

[[  4   5  -1   2   3]
 [ 12  13   0  10   3]
 [ -8  -8   5 -11   4]
 [ 16  18  -7  20   4]
 [ -4  -9  31 -31  -1]]
[ 34  93 -33 131 -58]


In [13]:
SolverLU(A, b)

array([1, 2, 3, 4, 5])

Curiosamente, la solución al sistema es el vector $(1, 2, 3, 4, 5)$

# Pivoteo Parcial

In [57]:
def Permutaciones(A, y):
    """
    Realiza el proceso de eliminación gaussiana con pivoteo parcial para una matriz A y vector y,
    generando una serie de matrices de permutación.

    El proceso intercambia filas de la matriz A para maximizar la estabilidad numérica y resolver
    sistemas lineales mediante factorización.

    Parámetros:
    A (numpy.ndarray): La matriz de coeficientes de entrada, cuadrada.
    y (numpy.ndarray): El vector columna de términos independientes.

    Retorna:
    tuple: Una tupla con los siguientes elementos:
        - Ps (list of numpy.ndarray): Lista de matrices de permutación que representan los intercambios de filas.
        - U (numpy.ndarray): La matriz A transformada después de aplicar las permutaciones.
        - b (numpy.ndarray): El vector y modificado acorde a las permutaciones aplicadas.
    """
    U = np.copy(A)  # Copia de la matriz A para evitar modificarla directamente
    b = np.copy(y)  # Copia del vector y para evitar modificarlo directamente
    Ps = []  # Lista para almacenar las matrices de permutación generadas en cada paso

    # Itera sobre cada columna de U para aplicar permutaciones
    for i in range(U.shape[0]):
        P = np.eye(U.shape[0])  # Crea una matriz identidad que actuará como permutación
        # Encuentra el índice de la fila con el valor máximo absoluto en la columna actual (a partir de la fila i)
        k = np.argmax(np.abs(U[i:, i])) + i
        U[[i, k]] = U[[k, i]]  # Intercambia las filas i y k en U
        P[[i, k]] = P[[k, i]]  # Registra el intercambio en la matriz de permutación P
        b[[i, k]] = b[[k, i]]  # Aplica el intercambio de filas en el vector b

        Ps.append(P)  # Guarda la matriz de permutación para el paso actual

    return Ps, U, b  # Retorna la lista de matrices de permutación, U modificada y b modificado


In [58]:
def PivoteoParcial(A, b):
    """
    Realiza el pivoteo parcial en la matriz A con el vector b, utilizando el método de permutaciones,
    y luego resuelve el sistema de ecuaciones resultante mediante la factorización LU.

    Parámetros:
    A (numpy.ndarray): La matriz de coeficientes del sistema, cuadrada.
    b (numpy.ndarray): El vector de términos independientes.

    Retorna:
    numpy.ndarray: El vector solución x que satisface Ax = b.
    """
    Ps, A_g, b_g = Permutaciones(A, b)  # Aplica permutaciones para hacer pivoteo en A y b
    x = SolverLU(A_g, b_g)  # Resuelve el sistema usando factorización LU
    return x


In [59]:
A = np.array([[4, -1, 3], [-8, 4, -7], [12, 1, 8]])
b = np.array([-8, 19, -19])
print(A)
print(b)

[[ 4 -1  3]
 [-8  4 -7]
 [12  1  8]]
[ -8  19 -19]


In [60]:
PivoteoParcial(A, b)

array([-1,  1,  0])

In [61]:
A = np.array([[1, 4, -2, 1], [-2, -4, -3, 1], [1, 16, -17, 9], [2, 4, -9, -3]])
b = np.array([3.5, -2.5, 15, 10.5])
print(A)
print(b)

[[  1   4  -2   1]
 [ -2  -4  -3   1]
 [  1  16 -17   9]
 [  2   4  -9  -3]]
[ 3.5 -2.5 15.  10.5]


In [62]:
PivoteoParcial(A, b)

array([-0.5,  1. , -0.5, -1. ])

In [63]:
A = np.array([[4, 5, -1, 2, 3], [12, 13, 0, 10, 3], [-8, -8, 5, -11, 4], [16, 18, -7, 20, 4], [-4, -9, 31, -31, -1]])
b = np.array([34, 93, -33, 131, -58])
print(A)
print(b)

[[  4   5  -1   2   3]
 [ 12  13   0  10   3]
 [ -8  -8   5 -11   4]
 [ 16  18  -7  20   4]
 [ -4  -9  31 -31  -1]]
[ 34  93 -33 131 -58]


In [64]:
PivoteoParcial(A, b)

array([0, 2, 5, 6, 4])

Es interesante analizar que, una vez que se realizan las permutaciones, en ocasiones, el resultado cambia.

# Pivoteo Total

Modifiquemos la función de permutaciones para que realice el pivoteo total:

In [76]:
def PermutacionTotal(A, y):
    """
    Realiza el pivoteo total en la matriz A con el vector y.
    Esto implica la búsqueda del mayor elemento en valor absoluto
    en la submatriz reducida, intercambiando tanto filas como columnas.
    """
    U = np.copy(A)
    b = np.copy(y)
    n = U.shape[0]
    Ps = []
    perm = np.arange(n) #Orden

    for i in range(n):
        # Encuentra la posición del mayor elemento en valor absoluto en la submatriz U[i:, i:]
        submatrix = np.abs(U[i:, i:])
        max_pos = np.unravel_index(np.argmax(submatrix), submatrix.shape)
        max_row, max_col = max_pos[0] + i, max_pos[1] + i

        # Intercambia filas en U y b
        if max_row != i:
            U[[i, max_row]] = U[[max_row, i]]
            b[[i, max_row]] = b[[max_row, i]]

        # Intercambia columnas en U y actualiza el orden en perm
        if max_col != i:
            U[:, [i, max_col]] = U[:, [max_col, i]]
            perm[[i, max_col]] = perm[[max_col, i]]

        # Registra la permutación aplicada
        P = np.eye(n)
        if max_row != i:
            P[[i, max_row]] = P[[max_row, i]]
        if max_col != i:
            P[:, [i, max_col]] = P[:, [max_col, i]]
        Ps.append(P)

    return Ps, U, b, perm


In [75]:
def LUConPivoteoTotal(A, y):
    #Realizamos el pivoteo total sobre la matriz A y el vector y
    Ps, U_permutada, b_permutada, perm = PermutacionTotal(A, y)

    # Realizamos la factorización LU sobre la matriz permutada
    L, U = FactLU(U_permutada)

    #Se ajusta el vector de términos independientes según las permutaciones aplicadas
    b_final = b_permutada

    #Regresa L, U, el vector permutado, y las permutaciones aplicadas
    return L, U, b_final, perm


In [73]:
def SolveLUConPivoteoTotal(A, b):
    L, U, b_permutado, perm = LUConPivoteoTotal(A, b)

    z = SustDelante(L, b_permutado)

    x_p = SustAtras(U, z)

    #Se revierte el orden de las permutaciones en x_p (el que permutamos)
    x = np.empty_like(x_p)
    for i, k in enumerate(perm):
        x[k] = x_p[i]

    return x


In [70]:
A = np.array([[4, -1, 3], [-8, 4, -7], [12, 1, 8]])
b = np.array([-8, 19, -19])
print(A)
print(b)

[[ 4 -1  3]
 [-8  4 -7]
 [12  1  8]]
[ -8  19 -19]


In [77]:
SolveLUConPivoteoTotal(A, b)

array([ 0,  0, -3])

In [78]:
A = np.array([[1, 4, -2, 1], [-2, -4, -3, 1], [1, 16, -17, 9], [2, 4, -9, -3]])
b = np.array([3.5, -2.5, 15, 10.5])
print(A)
print(b)

[[  1   4  -2   1]
 [ -2  -4  -3   1]
 [  1  16 -17   9]
 [  2   4  -9  -3]]
[ 3.5 -2.5 15.  10.5]


In [81]:
SolveLUConPivoteoTotal(A, b)

array([-0.5,  1. , -0.5, -1. ])

In [82]:
A = np.array([[4, 5, -1, 2, 3], [12, 13, 0, 10, 3], [-8, -8, 5, -11, 4], [16, 18, -7, 20, 4], [-4, -9, 31, -31, -1]])
b = np.array([34, 93, -33, 131, -58])
print(A)
print(b)

[[  4   5  -1   2   3]
 [ 12  13   0  10   3]
 [ -8  -8   5 -11   4]
 [ 16  18  -7  20   4]
 [ -4  -9  31 -31  -1]]
[ 34  93 -33 131 -58]


In [83]:
SolveLUConPivoteoTotal(A, b)

array([-3,  5,  4,  5,  4])