<a href="https://colab.research.google.com/github/jorgg3/Proyecto-2/blob/main/Ejercicio_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 2: Solución a Sistemas de Ecuaciones Lineales
**Problemas Computacionales**\
Alumno: Martínez de la Cruz José Jorge\
Profesor: César Carreón Otañez\
Ayudante:  Jesús Iván Coss Calderón

23) Programar la Factorización de Cholesky dada por:\
a) $A = LL^{T}$, $L$ triangular inferior\
b) $A = LDL^T$, $L$ triangular inferior y $D$ diagonal.

b) En la realización de éste inciso, se hará uso de la factorización LU para obtener las matríces solicitadas:


In [18]:
import numpy as np

def FactLU(A):
    """
    Realiza la factorización LU de una matriz cuadrada A, descomponiéndola en el producto de
    una matriz triangular inferior L y una matriz triangular superior U, tales que A = LU.

    Parámetros:
    A (numpy.ndarray): La matriz cuadrada que se desea factorizar.

    Retorna:
    tuple: Una tupla (L, U), donde:
        - L (numpy.ndarray): Matriz triangular inferior.
        - U (numpy.ndarray): Matriz triangular superior.
    """
    U = np.copy(A)  # Copia la matriz A para trabajar en U sin modificar A directamente
    n = A.shape[1]  # Número de columnas (y filas, ya que es cuadrada)
    L = np.eye(n)  # Inicializa L como la matriz identidad de tamaño n

    # Realiza iteración sobre las columnas para la construcción de L y U
    for j in range(n):
        Lj = np.eye(n)  # Matriz identidad que actuará como transformadora en cada paso
        for i in range(j + 1, n):
            Lj[i, j] = -U[i, j] / U[j, j]  # Calcula el multiplicador para hacer ceros en U
        L = L @ Lj  # Acumula el producto de matrices transformadoras en L
        U = Lj @ U  # Aplica la transformación en U para hacer ceros debajo del pivote actual

    # Ajusta L para obtener la matriz triangular inferior correcta
    L = 2 * np.eye(n) - L

    return L, U  # Retorna las matrices L y U resultantes

In [19]:
import numpy as np

def CholeskyB(A):
    """
    Realiza una factorización alternativa de Cholesky para una matriz simétrica y definida positiva A.
    Esta versión descompone A en el producto de una matriz triangular inferior L,
    una matriz diagonal D, y la transpuesta de L, de modo que A = L * D * L^T.

    Parámetros:
    A (numpy.ndarray): La matriz simétrica y definida positiva que se desea factorizar.

    Retorna:
    tuple: Una tupla (L, D), donde:
        - L (numpy.ndarray): Matriz triangular inferior obtenida de la factorización LU.
        - D (numpy.ndarray): Matriz diagonal con los elementos de la diagonal de U.
    """
    # Inicializa D como una matriz identidad del mismo tamaño que A
    D = np.eye(len(A))

    # Realiza la factorización LU de A, obteniendo L y U
    L, U = FactLU(A)

    # Llena la matriz D con los elementos de la diagonal de U
    for i in range(len(U)):
        D[i][i] = U[i][i]

    return L, D  # Retorna las matrices L y D resultantes


**Ejemplo:**

In [20]:
A = np.array([
    [4, 1, 2],
    [1, 3, 0],
    [2, 0, 2]
])
A

array([[4, 1, 2],
       [1, 3, 0],
       [2, 0, 2]])

In [27]:
L = CholeskyB(A)[0]
LT = L.T
D = CholeskyB(A)[1]

In [28]:
L@D@LT

array([[ 4.00000000e+00,  1.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  3.00000000e+00, -1.38777878e-17],
       [ 2.00000000e+00,  0.00000000e+00,  2.00000000e+00]])

a) Usaremos el ejercicio anterior para terminar el ejercicio

In [29]:
import numpy as np

def Cholesky(A):
    """
    Realiza la factorización de Cholesky de una matriz simétrica y definida positiva A.
    La función descompone A en el producto de una matriz triangular inferior L y su transpuesta,
    de modo que A = L * L^T.

    Este método utiliza una factorización intermedia `L * D * L^T`, donde D es una matriz diagonal,
    y luego ajusta D para obtener la forma estándar de la factorización de Cholesky.

    Parámetros:
    A (numpy.ndarray): La matriz simétrica y definida positiva que se desea factorizar.

    Retorna:
    numpy.ndarray: La matriz triangular inferior L tal que A = L * L^T.
    """
    # Inicializa Du como una matriz identidad que contendrá la raíz cuadrada de los elementos de D en la diagonal
    Du = np.eye(len(A))

    # Descomposición preliminar usando CholeskyB para obtener matrices L y D
    L, D = CholeskyB(A)

    # Reemplaza la diagonal de Du con la raíz cuadrada de los elementos de la diagonal de D
    for i in range(len(A)):
        Du[i][i] = np.sqrt(D[i][i])

    # Devuelve el producto L @ Du, que representa la matriz L de la factorización de Cholesky estándar
    return L @ Du


**Ejemplo**


In [30]:
L = Cholesky(A)
L

array([[ 2.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.6583124 ,  0.        ],
       [ 1.        , -0.30151134,  0.95346259]])

In [32]:
Lt = L.T
Lt

array([[ 2.        ,  0.5       ,  1.        ],
       [ 0.        ,  1.6583124 , -0.30151134],
       [ 0.        ,  0.        ,  0.95346259]])

In [33]:
L@Lt

array([[ 4.00000000e+00,  1.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  3.00000000e+00, -4.93833114e-18],
       [ 2.00000000e+00, -4.93833114e-18,  2.00000000e+00]])