<a href="https://colab.research.google.com/github/jorgg3/Proyecto-2/blob/main/Ejercicio_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 2: Solución a Sistemas de Ecuaciones Lineales
**Problemas Computacionales**\
Alumno: Martínez de la Cruz José Jorge\
Profesor: César Carreón Otañez\
Ayudante:  Jesús Iván Coss Calderón

22) Sea el sistema $Ax = b$ dado por:
$$
A =\begin{bmatrix}
  9 & -4 & 1 & 0 & \dots & 0 & 0 & 0 \\
 -4 & 6 & -4 & 0 & \dots & 0 & 0 & 0 \\
  1 & -4 & 6 & \dots & 0 & 0 & 0 & 0 \\
 \vdots & \vdots & \vdots & \ddots & \vdots & \vdots & \vdots & \vdots \\
  0 & 0 & 0 & \dots & 6 & -4 & 1 \\
  0 & 0 & 0 & \dots & -4 & 5 & -2 \\
  0 & 0 & 0 & \dots & 1 & -2 & 1 \\
\end{bmatrix}
$$
Tomando $b = [1, 1, ..., 1]^t$, para $n = 100$, resolver por:

a) Factorización $LU$

In [1]:
import numpy as np

def FactLU(A):
    """
    Realiza la factorización LU de una matriz cuadrada A, descomponiéndola en el producto de
    una matriz triangular inferior L y una matriz triangular superior U, tales que A = LU.

    Parámetros:
    A (numpy.ndarray): La matriz cuadrada que se desea factorizar.

    Retorna:
    tuple: Una tupla (L, U), donde:
        - L (numpy.ndarray): Matriz triangular inferior.
        - U (numpy.ndarray): Matriz triangular superior.
    """
    U = np.copy(A)  # Copia la matriz A para trabajar en U sin modificar A directamente
    n = A.shape[1]  # Número de columnas (y filas, ya que es cuadrada)
    L = np.eye(n)  # Inicializa L como la matriz identidad de tamaño n

    # Realiza iteración sobre las columnas para la construcción de L y U
    for j in range(n):
        Lj = np.eye(n)  # Matriz identidad que actuará como transformadora en cada paso
        for i in range(j + 1, n):
            Lj[i, j] = -U[i, j] / U[j, j]  # Calcula el multiplicador para hacer ceros en U
        L = L @ Lj  # Acumula el producto de matrices transformadoras en L
        U = Lj @ U  # Aplica la transformación en U para hacer ceros debajo del pivote actual

    # Ajusta L para obtener la matriz triangular inferior correcta
    L = 2 * np.eye(n) - L

    return L, U  # Retorna las matrices L y U resultantes

In [2]:
def SustDelante(L,b):
  x=np.zeros_like(b)
  n=L.shape[0]# cantidad de renglones de L
  for i in range(n):
    sum=0.0
    for j in range(i):
      sum+=L[i,j]*x[j]
    x[i]=(b[i]-sum)/L[i,i]

  return x

In [3]:
def SustAtras(U,y):
  x=np.zeros_like(y)
  n=U.shape[0]# cantidad de renglones de U
  x[n-1]=y[n-1]/U[n-1][n-1]

  for i in range(n-2,-1,-1):
    sum=0.0
    for j in range(i+1,n):
      sum+=U[i,j]*x[j]
    x[i]=(y[i]-sum)/U[i,i]

  return x


In [4]:
def SolverLU(A,b):
  L,U=FactLU(A)
  y=SustDelante(L,b)
  x=SustAtras(U,y)

  return x

Primero, haremos un algoritmo que haga una matríz con las bandas necesarias:

In [20]:
n = 100
A = np.zeros((n, n))

# Llenamos las bandas
for i in range(n):
    A[i, i] = 6  # Banda diagonal
    if i > 0:
        A[i, i-1] = -4  # Banda por debajo de la diagonal
        A[i-1, i] = -4  # Banda por encima de la diagonal
    if i > 1:
       A[i, i-2] = 1  # Banda dos posiciones debajo de la diagonal
       A[i-2, i] = 1  # Banda dos posiciones arriba de la diagonal

print(A)

[[ 6. -4.  1. ...  0.  0.  0.]
 [-4.  6. -4. ...  0.  0.  0.]
 [ 1. -4.  6. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  6. -4.  1.]
 [ 0.  0.  0. ... -4.  6. -4.]
 [ 0.  0.  0. ...  1. -4.  6.]]


Ahora, cambiamos las entradas que hacen a la matríz simétrica:

In [21]:
A [0][0] = 9
A[99][98] = -2
A[98][99]= -2
A[98][98]=5
A[99][99]=1

In [8]:
print(A)

[[ 9. -4.  1. ...  0.  0.  0.]
 [-4.  6. -4. ...  0.  0.  0.]
 [ 1. -4.  6. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  6. -4.  1.]
 [ 0.  0.  0. ... -4.  5. -2.]
 [ 0.  0.  0. ...  1. -2.  1.]]


Ya tenemos la matríz, ahora generemos el vector y luego resolvamos por $LU$

In [11]:
b = np.ones(100)

In [12]:
SolverLU(A, b)

array([1.26250000e+03, 7.47500000e+03, 1.85385000e+04, 3.43550000e+04,
       5.48275000e+04, 7.98600000e+04, 1.09357500e+05, 1.43226000e+05,
       1.81372500e+05, 2.23705000e+05, 2.70132500e+05, 3.20565000e+05,
       3.74913500e+05, 4.33090000e+05, 4.95007500e+05, 5.60580000e+05,
       6.29722500e+05, 7.02351000e+05, 7.78382500e+05, 8.57735000e+05,
       9.40327500e+05, 1.02608000e+06, 1.11491350e+06, 1.20675000e+06,
       1.30151250e+06, 1.39912500e+06, 1.49951250e+06, 1.60260100e+06,
       1.70831750e+06, 1.81659000e+06, 1.92734750e+06, 2.04052000e+06,
       2.15603850e+06, 2.27383500e+06, 2.39384250e+06, 2.51599500e+06,
       2.64022750e+06, 2.76647600e+06, 2.89467750e+06, 3.02477000e+06,
       3.15669250e+06, 3.29038500e+06, 3.42578850e+06, 3.56284500e+06,
       3.70149750e+06, 3.84169000e+06, 3.98336750e+06, 4.12647600e+06,
       4.27096250e+06, 4.41677500e+06, 4.56386250e+06, 4.71217500e+06,
       4.86166350e+06, 5.01228000e+06, 5.16397750e+06, 5.31671000e+06,
      

Contamos con las 100 soluciones que nos proporciona el método $LU$

c) Verificar que la matriz $A$ tiene una factizaci ́on de la forma $A = RR^T$ donde $R$ es una matriz triangular superior de la forma:

\begin{bmatrix}
  2 & -2 & 1 & 0 & \dots & 0 & 0 & 0 \\
  0 & 1 & -2 & 0 & \dots & 0 & 0 & 0 \\
  0 & 0 & 1 & \dots & 0 & 0 & 0 & 0 \\
  \vdots & \vdots & \vdots & \ddots & \vdots & \vdots & \vdots & \vdots \\
  0 & 0 & 0 & \dots & 1 & -2 & 1 \\
  0 & 0 & 0 & \dots & 0 & 1 & -2 \\
  0 & 0 & 0 & \dots & 0 & 0 & 1 \\
\end{bmatrix}



In [17]:
n = 100
R = np.zeros((n, n))

# Asignaremos los valores de cada banda diagonal con el método np.fill_diagonal
np.fill_diagonal(R, 1)           # Diagonal principal con 1
np.fill_diagonal(R[:, 1:], -2)     # Banda superior inmediata con 2
np.fill_diagonal(R[:, 2:], 1)     # Segunda banda superior con 1
R[0][0] = 2 #Hay un cambio en el primer elemento de la matríz
print(R)

[[ 2. -2.  1. ...  0.  0.  0.]
 [ 0.  1. -2. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  1. -2.  1.]
 [ 0.  0.  0. ...  0.  1. -2.]
 [ 0.  0.  0. ...  0.  0.  1.]]


In [23]:
RT = R.T
A == R@RT

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

Notemos que, A sí tiene la descomposición en $RR^T$. Crea una rutina que resuelva el sistema sabiendo esta factorización

El sistema se puede reescribir como $RR^T x = b$, haciendo $Ry = b$, entonces $R^Tx = y$

In [33]:
def RRT(R, b):
  y= SustAtras(R,b)
  x=SustDelante(R.T,y)
  return x

Para $n = 1000$ resolver el sistema.

In [30]:
n = 1000
R = np.zeros((n, n))

# Asignaremos los valores de cada banda diagonal con el método np.fill_diagonal
np.fill_diagonal(R, 1)           # Diagonal principal con 1
np.fill_diagonal(R[:, 1:], -2)     # Banda superior inmediata con 2
np.fill_diagonal(R[:, 2:], 1)     # Segunda banda superior con 1
R[0][0] = 2 #Hay un cambio en el primer elemento de la matríz


In [32]:
b = np.ones(1000)

In [34]:
RRT(R, b)

array([1.25125000e+05, 7.49750000e+05, 1.87287600e+06, 3.49350500e+06,
       5.61064000e+06, 8.22328500e+06, 1.13304450e+07, 1.49311260e+07,
       1.90243350e+07, 2.36090800e+07, 2.86843700e+07, 3.42492150e+07,
       4.03026260e+07, 4.68436150e+07, 5.38711950e+07, 6.13843800e+07,
       6.93821850e+07, 7.78636260e+07, 8.68277200e+07, 9.62734850e+07,
       1.06199940e+08, 1.16606105e+08, 1.27491001e+08, 1.38853650e+08,
       1.50693075e+08, 1.63008300e+08, 1.75798350e+08, 1.89062251e+08,
       2.02799030e+08, 2.17007715e+08, 2.31687335e+08, 2.46836920e+08,
       2.62455501e+08, 2.78542110e+08, 2.95095780e+08, 3.12115545e+08,
       3.29600440e+08, 3.47549501e+08, 3.65961765e+08, 3.84836270e+08,
       4.04172055e+08, 4.23968160e+08, 4.44223626e+08, 4.64937495e+08,
       4.86108810e+08, 5.07736615e+08, 5.29819955e+08, 5.52357876e+08,
       5.75349425e+08, 5.98793650e+08, 6.22689600e+08, 6.47036325e+08,
       6.71832876e+08, 6.97078305e+08, 7.22771665e+08, 7.48912010e+08,
      

Nos proporciona los 1000 valores de solución.

b) Crear una rutina (tipo banda) para la estructura de la matriz y resolver.