<a href="https://colab.research.google.com/github/jorgg3/Proyecto-2/blob/main/Ejercicio_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 2: Solución a Sistemas de Ecuaciones Lineales
**Problemas Computacionales**\
Alumno: Martínez de la Cruz José Jorge\
Profesor: César Carreón Otañez\
Ayudante:  Jesús Iván Coss Calderón

In [4]:
import numpy as np

20) Dada la matriz
\begin{bmatrix}
  1 & 0 & 0 & 0 & 1 \\
 -1 & 1 & 0 & 0 & 1 \\
 -1 & -1 & 1 & 0 & 1 \\
 -1 & -1 & -1 & 1 & 1 \\
 -1 & -1 & -1 & -1 & 1 \\
\end{bmatrix}


In [18]:
A = np.array([[1,0,0,0,1],[-1,1,0,0,1],[-1,-1,1,0,1],[-1,-1,-1,1,1],[-1,-1,-1,-1,1]])
print(A)


[[ 1  0  0  0  1]
 [-1  1  0  0  1]
 [-1 -1  1  0  1]
 [-1 -1 -1  1  1]
 [-1 -1 -1 -1  1]]


a) ¿Qué sucede cuando se usa Eliminación Gaussina con pivoteo parcial?.

Para ello, ajustemos el programa para que realice el pivoteo parcial:

In [6]:
def Paso1(M):
    for k in range(0,len(M)): #Para cada una de las columnas:
      #print(f"k = {k}")
      columnas = [] #Guarda los elementos de la columna
      for i in range (k,len(M)):
        columnas.append(M[i][k])
      t = 0
      s = k + columnas.index(max(columnas))
      for c in columnas:
        if c == 0:
          #print(f"col = {columnas}, c = {c}")
          t += 1
      if t != 0 and max(columnas) != 0: #Si algún elemento de la columna es 0 y el máximo no es 0
          M[k], M[s] = M[s], M[k] #Intercambia renglones
          #print(f"cambio con s= {s} = \n {np.array(M)}")


      for j in range(k+1, len(M) ):
        if M[k][k] != 0:
          a= -M[j][k]/M[k][k] #Pibote
          M[j] = list(np.array(M[k])*a + M[j]) #Operaciones elementales
        #print(f"escalonado = \n{np.array(M)}")
    return(np.array(M))


In [8]:
def Paso2 (B):
  #print(np.array(B))
  for i in range(len(B)-1, -1, -1): # Hacemos el procedimiento analogo con los indices en reversa
  #para la columna 2:
    for k in range(i-1,-1,-1):
        if B[k][i] != 0:
          a = -B[k][i]/B[i][i]
          B[k] = (a* (np.array(B[i]))) + B[k]
  return(np.array(B))

In [9]:
def GaussPP(Z): #Unimos ambas funciones
  Z1 = Paso1(Z)

  Z2 = Paso2(Z1)
  return(Z2)

In [21]:
A_ = GaussPP(A)
print(A_)

[[ 1  0  0  0  0]
 [ 0  1  0  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0 16]]


La matríz queda diagonalizada de una manera partícular pues hay un factor $16$ en el último elemento.

(b) Usar Eliminación Gaussina con pivoteo parcial para resolver sistemas de varios tamaños (al menos 5) con vectores b elegidos por cualquier criterio. Describir como se comporta la condición de la matriz.

Usaremos la norma 1, para describir la condición de la matríz, en el caso de la matríz anterior:


In [11]:
def norma1 (A) :
  V = [] #Vector que guardará la suma de los valores absolutos por columna
  for j in range(len(A[0])):
    x = 0 #Para cada columna, comenzamos con 0
    for i in range(len(A)):
      x = x + abs(A[i][j]) #Empezamos a sumar los elementos con valor absoluto
    V.append(x)
  return max(V) #Retornamos el máximo

In [22]:
print(f"La condición de A = {norma1(A)* norma1(np.linalg.inv(A))}")

La condición de A = 31.0


$B=
\begin{bmatrix}
  1 & 0 & 0 & 0 & 0 & 1 \\
 -1 & 1 & 0 & 0 & 0 & 1 \\
 -1 & -1 & 1 & 0 & 0 & 1 \\
 -1 & -1 & -1 & 1 & 0 & 1 \\
 -1 & -1 & -1 & -1 & 1 & 1 \\
 -1 & -1 & -1 & -1 & -1 & 1 \\
\end{bmatrix}$

In [16]:
B = np.array([[1,0,0,0,0,1],[-1,1,0,0,0,1],[-1,-1,1,0,0,1],[-1,-1,-1,1,0,1],[-1,-1,-1, -1,1,1],[-1,-1,-1,-1,1,1]])
print(B)

[[ 1  0  0  0  0  1]
 [-1  1  0  0  0  1]
 [-1 -1  1  0  0  1]
 [-1 -1 -1  1  0  1]
 [-1 -1 -1 -1  1  1]
 [-1 -1 -1 -1  1  1]]


En tamaño 6, la matríz es singular, por lo tanto $Cond(B) = ∞$

$C = \begin{bmatrix}
  1 & 0 & 1 \\
 -1 & 1 & 1 \\
 -1 & -1 & 1 \\
\end{bmatrix}
$

In [25]:
C = np.array([[1,0,1],[-1,1,1],[-1,-1,1]])
print(C)

[[ 1  0  1]
 [-1  1  1]
 [-1 -1  1]]


In [26]:
print(f"La condición de C = {norma1(C)* norma1(np.linalg.inv(C))}")

La condición de C = 3.0


$D = \begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
-1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
-1 & -1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
-1 & -1 & -1 & 1 & 0 & 0 & 0 & 0 & 0 & 1 \\
-1 & -1 & -1 & -1 & 1 & 0 & 0 & 0 & 0 & 1 \\
-1 & -1 & -1 & -1 & -1 & 1 & 0 & 0 & 0 & 1 \\
-1 & -1 & -1 & -1 & -1 & -1 & 1 & 0 & 0 & 1 \\
-1 & -1 & -1 & -1 & -1 & -1 & -1 & 1 & 0 & 1 \\
-1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & 1 & 1 \\
-1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & 1 \\
\end{bmatrix} $


In [27]:

D = np.zeros((10, 10))
np.fill_diagonal(D, 1)
for i in range(1, 10):
    D[i, :i] = -1
D[:, -1] = 1

print(D)


[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [-1. -1.  1.  0.  0.  0.  0.  0.  0.  1.]
 [-1. -1. -1.  1.  0.  0.  0.  0.  0.  1.]
 [-1. -1. -1. -1.  1.  0.  0.  0.  0.  1.]
 [-1. -1. -1. -1. -1.  1.  0.  0.  0.  1.]
 [-1. -1. -1. -1. -1. -1.  1.  0.  0.  1.]
 [-1. -1. -1. -1. -1. -1. -1.  1.  0.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.  1.]]


In [28]:
print(f"La condición de D = {norma1(D)* norma1(np.linalg.inv(D))}")

La condición de D = 10.0


$ E= \begin{bmatrix}
1 & 1 \\
-1 & 1
\end{bmatrix}
$

In [29]:
E = np.array([[1,1],[-1,1]])
print(E)

[[ 1  1]
 [-1  1]]


In [30]:
print(f"La condición de E = {norma1(E)* norma1(np.linalg.inv(E))}")

La condición de E = 2.0


La condición de la matríz disminuye conforme el tamaño disminuye, en tamaño 6 la matríz es singular, ahora resolvamos algunos de los sistemas con un vector partícular:

In [31]:
def EPaso1(M):
    for k in range(0,len(M)-1): #Para cada una de las columnas:
      #print(f"k = {k}")
      columnas = [] #Guarda los elementos de la columna
      for i in range (k,len(M)):
        columnas.append(M[i][k])
      t = 0
      s = k + columnas.index(max(columnas))
      for c in columnas:
        if c == 0:
          #print(f"col = {columnas}, c = {c}")
          t += 1
      if t != 0 and max(columnas) != 0: #Si algún elemento de la columna es 0 y el máximo no es 0
          M[k], M[s] = M[s], M[k] #Intercambia renglones
          #print(f"cambio con s= {s} = \n {np.array(M)}")


      for j in range(k+1, len(M) ):
        if M[k][k] != 0:
          a= -M[j][k]/M[k][k] #Pibote
          M[j] = list(np.array(M[k])*a + M[j]) #Operaciones elementales
        #print(f"escalonado = \n{np.array(M)}")
    return(np.array(M))
def EPaso2 (B):
  #print(np.array(B))
  for i in range(len(B)-1, -1, -1): # Hacemos el procedimiento analogo con los indices en reversa
  #para la columna 2:
    for k in range(i-1,-1,-1):
        if B[k][i] != 0:
          a = -B[k][i]/B[i][i]
          B[k] = (a* (np.array(B[i]))) + B[k]
  return(np.array(B))
def SolveGauss(Z): #Unimos ambas funciones
  Z1 = EPaso1(Z)

  Z2 = EPaso2(Z1)
  return(Z2)

En cualquier tamaño, la solución será el vector $b = [1, 2, ..., n]$

In [32]:
A = np.array([[1,0,0,0,1, 1],[-1,1,0,0,1,2],[-1,-1,1,0,1, 3],[-1,-1,-1,1,1, 4],[-1,-1,-1,-1,1, 5]])
print(A)


[[ 1  0  0  0  1  1]
 [-1  1  0  0  1  2]
 [-1 -1  1  0  1  3]
 [-1 -1 -1  1  1  4]
 [-1 -1 -1 -1  1  5]]


In [33]:
SolveGauss(A)

array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0, 16, 31]])

La solución es la trivial con exepción del $x_5 = \frac{31}{16}$

In [34]:
B = np.array([[1,0,0,0,0,1, 1],[-1,1,0,0,0,1, 2],[-1,-1,1,0,0,1, 3],[-1,-1,-1,1,0,1, 4],[-1,-1,-1, -1,1,1, 5],[-1,-1,-1,-1,1,1, 6]])
print(B)

[[ 1  0  0  0  0  1  1]
 [-1  1  0  0  0  1  2]
 [-1 -1  1  0  0  1  3]
 [-1 -1 -1  1  0  1  4]
 [-1 -1 -1 -1  1  1  5]
 [-1 -1 -1 -1  1  1  6]]


In [35]:
SolveGauss(B)

<ipython-input-31-6e54928a7929>:30: RuntimeWarning: divide by zero encountered in scalar divide
  a = -B[k][i]/B[i][i]
<ipython-input-31-6e54928a7929>:31: RuntimeWarning: invalid value encountered in multiply
  B[k] = (a* (np.array(B[i]))) + B[k]
<ipython-input-31-6e54928a7929>:31: RuntimeWarning: invalid value encountered in cast
  B[k] = (a* (np.array(B[i]))) + B[k]
<ipython-input-31-6e54928a7929>:30: RuntimeWarning: overflow encountered in scalar negative
  a = -B[k][i]/B[i][i]


array([[-9223372036854775808, -9223372036854775808, -9223372036854775808,
        -9223372036854775808, -9223372036854775808, -9223372036854775808,
        -9223372036854775808],
       [-9223372036854775808, -9223372036854775808, -9223372036854775808,
        -9223372036854775808, -9223372036854775808, -9223372036854775808,
        -9223372036854775808],
       [-9223372036854775808, -9223372036854775808, -9223372036854775808,
        -9223372036854775808, -9223372036854775808, -9223372036854775808,
        -9223372036854775808],
       [-9223372036854775808, -9223372036854775808, -9223372036854775808,
        -9223372036854775808, -9223372036854775808, -9223372036854775808,
        -9223372036854775808],
       [-9223372036854775808, -9223372036854775808, -9223372036854775808,
        -9223372036854775808, -9223372036854775808, -9223372036854775808,
        -9223372036854775808],
       [                   0,                    0,                    0,
                           0,  

No hay solución pues como se dijo anteriormente, es una matríz singular

In [36]:
C = np.array([[1,0,1, 1],[-1,1,1, 2],[-1,-1,1, 3]])
print(C)

[[ 1  0  1  1]
 [-1  1  1  2]
 [-1 -1  1  3]]


In [37]:
SolveGauss(C)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 7]])

La solución es la trivial a excepción de $x_3 = \frac{7}{4}$

In [43]:
D = np.zeros((11, 11))
np.fill_diagonal(D, 1)
for i in range(1, 11):
    D[i, :i] = -1
D[:, -2] = 1
for j in range (0, 11):
  D[j, -1] = j+1

print(D)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [-1.  1.  0.  0.  0.  0.  0.  0.  0.  1.  2.]
 [-1. -1.  1.  0.  0.  0.  0.  0.  0.  1.  3.]
 [-1. -1. -1.  1.  0.  0.  0.  0.  0.  1.  4.]
 [-1. -1. -1. -1.  1.  0.  0.  0.  0.  1.  5.]
 [-1. -1. -1. -1. -1.  1.  0.  0.  0.  1.  6.]
 [-1. -1. -1. -1. -1. -1.  1.  0.  0.  1.  7.]
 [-1. -1. -1. -1. -1. -1. -1.  1.  0.  1.  8.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  9.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.  1. 10.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.  1. 11.]]


In [44]:
SolveGauss(D)

array([[  1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 512.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.]])

Aquí la solución no tiene mucho sentido pues tenemos una ecuación $0 = 1$

In [45]:
E = np.array([[1,1, 1],[-1,1, 2]])
print(E)

[[ 1  1  1]
 [-1  1  2]]


In [46]:
SolveGauss(E)

array([[1, 0, 0],
       [0, 2, 3]])

La solución es la trivial a exepción del $x_2 = \frac{3}{2}$

c) Escribir una rutina que factorice la matriz (LU) con pivoteo total.

In [47]:
def FactLU(A):
  U=np.copy(A)
  n=A.shape[1]
  L=np.eye(n)
  for j in range(n):
    Lj=np.eye(n)
    for i in range(j+1,n):
      Lj[i,j]=-U[i,j]/U[j,j]
    L=L@Lj
    #print(Lj,j)
    U=Lj@U
  L=2*np.eye(n)-L
  return L,U

def SustDelante(L,b):
  x=np.zeros_like(b)
  n=L.shape[0]# cantidad de renglones de L
  for i in range(n):
    sum=0.0
    for j in range(i):
      sum+=L[i,j]*x[j]
    x[i]=(b[i]-sum)/L[i,i]

  return x

def SustAtras(U,y):
  x=np.zeros_like(y)
  n=U.shape[0]# cantidad de renglones de U
  x[n-1]=y[n-1]/U[n-1][n-1]

  for i in range(n-2,-1,-1):
    sum=0.0
    for j in range(i+1,n):
      sum+=U[i,j]*x[j]
    x[i]=(y[i]-sum)/U[i,i]

  return x

def SolverLU(A,b):
  L,U=FactLU(A)
  y=SustDelante(L,b)
  x=SustAtras(U,y)

  return x

In [48]:
def PermutacionTotal(A, y):
    """
    Realiza el pivoteo total en la matriz A con el vector y.
    Esto implica la búsqueda del mayor elemento en valor absoluto
    en la submatriz reducida, intercambiando tanto filas como columnas.
    """
    U = np.copy(A)
    b = np.copy(y)
    n = U.shape[0]
    Ps = []
    perm = np.arange(n) #Orden

    for i in range(n):
        # Encuentra la posición del mayor elemento en valor absoluto en la submatriz U[i:, i:]
        submatrix = np.abs(U[i:, i:])
        max_pos = np.unravel_index(np.argmax(submatrix), submatrix.shape)
        max_row, max_col = max_pos[0] + i, max_pos[1] + i

        # Intercambia filas en U y b
        if max_row != i:
            U[[i, max_row]] = U[[max_row, i]]
            b[[i, max_row]] = b[[max_row, i]]

        # Intercambia columnas en U y actualiza el orden en perm
        if max_col != i:
            U[:, [i, max_col]] = U[:, [max_col, i]]
            perm[[i, max_col]] = perm[[max_col, i]]

        # Registra la permutación aplicada
        P = np.eye(n)
        if max_row != i:
            P[[i, max_row]] = P[[max_row, i]]
        if max_col != i:
            P[:, [i, max_col]] = P[:, [max_col, i]]
        Ps.append(P)

    return Ps, U, b, perm


In [49]:
def LUConPivoteoTotal(A, y):
    #Realizamos el pivoteo total sobre la matriz A y el vector y
    Ps, U_permutada, b_permutada, perm = PermutacionTotal(A, y)

    # Realizamos la factorización LU sobre la matriz permutada
    L, U = FactLU(U_permutada)

    #Se ajusta el vector de términos independientes según las permutaciones aplicadas
    b_final = b_permutada

    #Regresa L, U, el vector permutado, y las permutaciones aplicadas
    return L, U, b_final, perm