<a href="https://colab.research.google.com/github/jorgg3/Proyecto-2/blob/main/Ejercicio_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 2: Solución a Sistemas de Ecuaciones Lineales
**Problemas Computacionales**\
Alumno: Martínez de la Cruz José Jorge\
Profesor: César Carreón Otañez\
Ayudante:  Jesús Iván Coss Calderón

24) Encontrar la factorización de Cholesky de A para las siguientes matríces:

Para ello, haremos uso de los códigos creados en el ejercicio 23

In [1]:
import numpy as np

def FactLU(A):
    """
    Realiza la factorización LU de una matriz cuadrada A, descomponiéndola en el producto de
    una matriz triangular inferior L y una matriz triangular superior U, tales que A = LU.

    Parámetros:
    A (numpy.ndarray): La matriz cuadrada que se desea factorizar.

    Retorna:
    tuple: Una tupla (L, U), donde:
        - L (numpy.ndarray): Matriz triangular inferior.
        - U (numpy.ndarray): Matriz triangular superior.
    """
    U = np.copy(A)  # Copia la matriz A para trabajar en U sin modificar A directamente
    n = A.shape[1]  # Número de columnas (y filas, ya que es cuadrada)
    L = np.eye(n)  # Inicializa L como la matriz identidad de tamaño n

    # Realiza iteración sobre las columnas para la construcción de L y U
    for j in range(n):
        Lj = np.eye(n)  # Matriz identidad que actuará como transformadora en cada paso
        for i in range(j + 1, n):
            Lj[i, j] = -U[i, j] / U[j, j]  # Calcula el multiplicador para hacer ceros en U
        L = L @ Lj  # Acumula el producto de matrices transformadoras en L
        U = Lj @ U  # Aplica la transformación en U para hacer ceros debajo del pivote actual

    # Ajusta L para obtener la matriz triangular inferior correcta
    L = 2 * np.eye(n) - L

    return L, U  # Retorna las matrices L y U resultantes

In [2]:
import numpy as np

def CholeskyB(A):
    """
    Realiza una factorización alternativa de Cholesky para una matriz simétrica y definida positiva A.
    Esta versión descompone A en el producto de una matriz triangular inferior L,
    una matriz diagonal D, y la transpuesta de L, de modo que A = L * D * L^T.

    Parámetros:
    A (numpy.ndarray): La matriz simétrica y definida positiva que se desea factorizar.

    Retorna:
    tuple: Una tupla (L, D), donde:
        - L (numpy.ndarray): Matriz triangular inferior obtenida de la factorización LU.
        - D (numpy.ndarray): Matriz diagonal con los elementos de la diagonal de U.
    """
    # Inicializa D como una matriz identidad del mismo tamaño que A
    D = np.eye(len(A))

    # Realiza la factorización LU de A, obteniendo L y U
    L, U = FactLU(A)

    # Llena la matriz D con los elementos de la diagonal de U
    for i in range(len(U)):
        D[i][i] = U[i][i]

    return L, D  # Retorna las matrices L y D resultantes


In [3]:
import numpy as np

def Cholesky(A):
    """
    Realiza la factorización de Cholesky de una matriz simétrica y definida positiva A.
    La función descompone A en el producto de una matriz triangular inferior L y su transpuesta,
    de modo que A = L * L^T.

    Este método utiliza una factorización intermedia `L * D * L^T`, donde D es una matriz diagonal,
    y luego ajusta D para obtener la forma estándar de la factorización de Cholesky.

    Parámetros:
    A (numpy.ndarray): La matriz simétrica y definida positiva que se desea factorizar.

    Retorna:
    numpy.ndarray: La matriz triangular inferior L tal que A = L * L^T.
    """
    # Inicializa Du como una matriz identidad que contendrá la raíz cuadrada de los elementos de D en la diagonal
    Du = np.eye(len(A))

    # Descomposición preliminar usando CholeskyB para obtener matrices L y D
    L, D = CholeskyB(A)

    # Reemplaza la diagonal de Du con la raíz cuadrada de los elementos de la diagonal de D
    for i in range(len(A)):
        Du[i][i] = np.sqrt(D[i][i])

    # Devuelve el producto L @ Du, que representa la matriz L de la factorización de Cholesky estándar
    return L @ Du


 $$
A = \begin{bmatrix}
  2 & -1 & 0 \\
  -1 & 2 & -1 \\
  0 & -1 & 2 \\
\end{bmatrix}
$$

In [15]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
L = Cholesky(A)
print(f"L =\n {L}")

L =
 [[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]


In [22]:
print(f"L = \n{CholeskyB(A)[0]}\n D=\n {CholeskyB(A)[1]}")

L = 
[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]]
 D=
 [[2.         0.         0.        ]
 [0.         1.5        0.        ]
 [0.         0.         1.33333333]]


 $$
B = \begin{bmatrix}
  4 & 1 & 1 & 1 \\
  1 & 3 & -1 & 1 \\
  1 & -1 & 2 & 0 \\
  1 & 1 & 0 & 2
\end{bmatrix}
$$

In [13]:
B = np.array([[4, 1, 1, 1], [1, 3, -1, 1], [1, -1, 2, 0], [1, 1, 0, 2]])
L = Cholesky(B)
print(f"L =\n {L}")

L =
 [[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [ 0.5        -0.75377836  1.08711461  0.        ]
 [ 0.5         0.45226702  0.0836242   1.24034735]]


In [21]:
print(f"L = \n{CholeskyB(B)[0]}\n D=\n {CholeskyB(B)[1]}")

L = 
[[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [ 0.25       -0.45454545  1.          0.        ]
 [ 0.25        0.27272727  0.07692308  1.        ]]
 D=
 [[4.         0.         0.         0.        ]
 [0.         2.75       0.         0.        ]
 [0.         0.         1.18181818 0.        ]
 [0.         0.         0.         1.53846154]]


 $$
C = \begin{bmatrix}
  4 & 1 & - 1& 0 \\
  1 & 3 & -1 & 0 \\
  -1 & -1 & 5 & 2 \\
  0 & 0 & 2 & 4
\end{bmatrix}
$$

In [12]:
C = np.array([[4, 1, -1, 0], [1, 3, -1, 0], [-1, -1, 5, 2], [0, 0, 2, 4]])
L = Cholesky(C)
print(f"L =\n {L}")

L =
 [[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [-0.5        -0.45226702  2.13200716  0.        ]
 [ 0.          0.          0.93808315  1.76635217]]


In [20]:
print(f"L = \n{CholeskyB(C)[0]}\n D=\n {CholeskyB(C)[1]}")

L = 
[[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [-0.25       -0.27272727  1.          0.        ]
 [ 0.          0.          0.44        1.        ]]
 D=
 [[4.         0.         0.         0.        ]
 [0.         2.75       0.         0.        ]
 [0.         0.         4.54545455 0.        ]
 [0.         0.         0.         3.12      ]]


 $$
D = \begin{bmatrix}
  6 & 2 & 1& -1 \\
  2 & 4 & 1 & 0 \\
  1 & 1 & 4 & -1 \\
  -1 & 0 & -1 & 3
\end{bmatrix}
$$

In [16]:
D = np.array([[6, 2, 1, -1], [2, 4, 1, 0], [1, 1, 4, -1], [-1, 0, -1, 3]])
L = Cholesky(D)
print(f"L =\n {L}")

L =
 [[ 2.44948974  0.          0.          0.        ]
 [ 0.81649658  1.82574186  0.          0.        ]
 [ 0.40824829  0.36514837  1.92353841  0.        ]
 [-0.40824829  0.18257419 -0.46788772  1.60657433]]


In [19]:
print(f"L = \n{CholeskyB(D)[0]}\n D=\n {CholeskyB(D)[1]}")

L = 
[[ 1.          0.          0.          0.        ]
 [ 0.33333333  1.          0.          0.        ]
 [ 0.16666667  0.2         1.          0.        ]
 [-0.16666667  0.1        -0.24324324  1.        ]]
 D=
 [[6.         0.         0.         0.        ]
 [0.         3.33333333 0.         0.        ]
 [0.         0.         3.7        0.        ]
 [0.         0.         0.         2.58108108]]
