# Práctica 2: Solución a Sistemas de Ecuaciones Lineales
**Problemas Computacionales**\
Alumno: Martínez de la Cruz José Jorge\
Profesor: César Carreón Otañez\
Ayudante:  Jesús Iván Coss Calderón

18) Dado el sistema $Ax = b$, resolver con eliminación Gaussiana para:
 $$
A = \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
\end{bmatrix},
b =\begin{bmatrix}
  2\\
  8\\
  10\\
\end{bmatrix}
$$
Para ello, realizaremos un programa que haga la eliminación gaussiana (mediante la eliminación de los elementos fuera de la diagonal), se hará en dos pasos donde se consigan matríces triangulares superior e inferior respectivamente
.

En este método, se usará pedirá que la matríz no sea cuadrada pues para encontrar la solución del sistema de ecuaciones, habrá que transformar el vector $b$ junto con la matríz $A$, por lo que hay que agregarlo al final como una columna extra.

In [22]:
import numpy as np

def Paso1(M):
    """
    Realiza el primer paso de un método de eliminación Gaussiana para una matriz dada.
    Este método pivotea filas para evitar ceros en la diagonal principal y luego realiza
    operaciones elementales para escalonar la matriz.

    Parámetros:
    M (list of lists): La matriz que se desea escalonar.

    Retorna:
    numpy.ndarray: La matriz escalonada después de la eliminación Gaussiana.
    """
    for k in range(len(M) - 1):  # Recorre cada columna de la matriz M
        # Realiza la eliminación Gaussiana para hacer ceros debajo del pivote
        for j in range(k + 1, len(M)):
            if M[k][k] != 0:  # Asegura que el pivote no sea cero
                a = -M[j][k] / M[k][k]  # Calcula el factor multiplicativo para la eliminación
                M[j] = list(np.array(M[k]) * a + M[j])  # Aplica operaciones elementales

    return np.array(M)  # Retorna la matriz escalonada como un array de NumPy


In [23]:
def Paso2(B):
    """
    Realiza el segundo paso de un método de eliminación Gaussiana para obtener una matriz en forma escalonada reducida.
    Este paso aplica eliminación hacia arriba para hacer ceros encima de los elementos en la diagonal principal.

    Parámetros:
    B (list of lists): La matriz en forma escalonada para ser convertida a forma escalonada reducida.

    Retorna:
    numpy.ndarray: La matriz en forma escalonada reducida.
    """
    # Recorre la matriz en reversa, comenzando desde la última fila hasta la primera
    for i in range(len(B) - 1, -1, -1):
        # Realiza eliminación hacia arriba en las filas superiores a la fila i
        for k in range(i - 1, -1, -1):
            if B[k][i] != 0:  # Solo realiza operaciones si el elemento no es cero
                a = -B[k][i] / B[i][i]  # Calcula el factor multiplicativo para eliminar el término
                B[k] = (a * np.array(B[i])) + B[k]  # Realiza la eliminación sumando la fila modificada

    return np.array(B)  # Retorna la matriz en forma escalonada reducida


In [24]:
def EGaussiana(Z):
    """
    Aplica el método de eliminación Gaussiana completo para transformar una matriz a su forma escalonada reducida.
    Esta función une dos pasos: el primero convierte la matriz a forma escalonada, y el segundo a forma escalonada reducida.

    Parámetros:
    Z (list of lists): La matriz que se desea transformar mediante el método de eliminación Gaussiana.

    Retorna:
    numpy.ndarray: La matriz en forma escalonada reducida.
    """
    Z1 = Paso1(Z)  # Aplica el primer paso de eliminación Gaussiana (forma escalonada)
    Z2 = Paso2(Z1)  # Aplica el segundo paso para reducir la forma escalonada
    return Z2  # Retorna la matriz en forma escalonada reducida


Observaciones: Esta es la eliminación gaussiana sin piboteo. Ahora sí, resolvamos el problema:

In [25]:
Ab = np.array([[1,2,3,2], [4,5,6,8], [7, 8, 9, 10]])
print(Ab)
Paso1(Ab)

[[ 1  2  3  2]
 [ 4  5  6  8]
 [ 7  8  9 10]]


array([[ 1,  2,  3,  2],
       [ 0, -3, -6,  0],
       [ 0,  0,  0, -4]])

Notemos que al hacer la primer eliminación gaussiana, el término que queda en la diagonal es 0, por lo que el sistema no tendría solución.

Usa factorización LU de $A$ para resolver el sistema $Ay = c$, donde:
$$
c =\begin{bmatrix}
  4\\
  8\\
  -6\\
\end{bmatrix}
$$


Aquí, usaremos los códigos trabajados en clase:


In [26]:
import numpy as np

def FactLU(A):
    """
    Realiza la factorización LU de una matriz cuadrada A, descomponiéndola en el producto de
    una matriz triangular inferior L y una matriz triangular superior U, tales que A = LU.

    Parámetros:
    A (numpy.ndarray): La matriz cuadrada que se desea factorizar.

    Retorna:
    tuple: Una tupla (L, U), donde:
        - L (numpy.ndarray): Matriz triangular inferior.
        - U (numpy.ndarray): Matriz triangular superior.
    """
    U = np.copy(A)  # Copia la matriz A para trabajar en U sin modificar A directamente
    n = A.shape[1]  # Número de columnas (y filas, ya que es cuadrada)
    L = np.eye(n)  # Inicializa L como la matriz identidad de tamaño n

    # Realiza iteración sobre las columnas para la construcción de L y U
    for j in range(n):
        Lj = np.eye(n)  # Matriz identidad que actuará como transformadora en cada paso
        for i in range(j + 1, n):
            Lj[i, j] = -U[i, j] / U[j, j]  # Calcula el multiplicador para hacer ceros en U
        L = L @ Lj  # Acumula el producto de matrices transformadoras en L
        U = Lj @ U  # Aplica la transformación en U para hacer ceros debajo del pivote actual

    # Ajusta L para obtener la matriz triangular inferior correcta
    L = 2 * np.eye(n) - L

    return L, U  # Retorna las matrices L y U resultantes

In [27]:
def SustDelante(L,b):
  x=np.zeros_like(b)
  n=L.shape[0]# cantidad de renglones de L
  for i in range(n):
    sum=0.0
    for j in range(i):
      sum+=L[i,j]*x[j]
    x[i]=(b[i]-sum)/L[i,i]

  return x

In [28]:
def SustAtras(U,y):
  x=np.zeros_like(y)
  n=U.shape[0]# cantidad de renglones de U
  x[n-1]=y[n-1]/U[n-1][n-1]

  for i in range(n-2,-1,-1):
    sum=0.0
    for j in range(i+1,n):
      sum+=U[i,j]*x[j]
    x[i]=(y[i]-sum)/U[i,i]

  return x


In [29]:
def SolverLU(A,b):
  L,U=FactLU(A)
  y=SustDelante(L,b)
  x=SustAtras(U,y)

  return x

Resolviendo el ejercicio:

In [30]:
A = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
c = [4, 8, -6]
A1 = FactLU(A)
A1

(array([[1., 0., 0.],
        [4., 1., 0.],
        [7., 2., 1.]]),
 array([[ 1.,  2.,  3.],
        [ 0., -3., -6.],
        [ 0.,  0.,  0.]]))

Nuevamente vemos que, no hay solución del sistema $Ux = y$, pues el último renglón de $U$ está lleno de $0$, lo que no permite hacer la sustitución hacia atrás.