<a href="https://colab.research.google.com/github/jorgg3/Proyecto-2/blob/main/Ejercicio19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 2: Solución a Sistemas de Ecuaciones Lineales
**Problemas Computacionales**\
Alumno: Martínez de la Cruz José Jorge\
Profesor: César Carreón Otañez\
Ayudante:  Jesús Iván Coss Calderón

In [1]:
#Cargamos la factorización LU:
import numpy as np

def FactLU(A):
    """
    Realiza la factorización LU de una matriz cuadrada A, descomponiéndola en el producto de
    una matriz triangular inferior L y una matriz triangular superior U, tales que A = LU.

    Parámetros:
    A (numpy.ndarray): La matriz cuadrada que se desea factorizar.

    Retorna:
    tuple: Una tupla (L, U), donde:
        - L (numpy.ndarray): Matriz triangular inferior.
        - U (numpy.ndarray): Matriz triangular superior.
    """
    U = np.copy(A)  # Copia la matriz A para trabajar en U sin modificar A directamente
    n = A.shape[1]  # Número de columnas (y filas, ya que es cuadrada)
    L = np.eye(n)  # Inicializa L como la matriz identidad de tamaño n

    # Realiza iteración sobre las columnas para la construcción de L y U
    for j in range(n):
        Lj = np.eye(n)  # Matriz identidad que actuará como transformadora en cada paso
        for i in range(j + 1, n):
            Lj[i, j] = -U[i, j] / U[j, j]  # Calcula el multiplicador para hacer ceros en U
        L = L @ Lj  # Acumula el producto de matrices transformadoras en L
        U = Lj @ U  # Aplica la transformación en U para hacer ceros debajo del pivote actual

    # Ajusta L para obtener la matriz triangular inferior correcta
    L = 2 * np.eye(n) - L

    return L, U  # Retorna las matrices L y U resultantes

In [2]:
def SustDelante(L,b):
  x=np.zeros_like(b)
  n=L.shape[0]# cantidad de renglones de L
  for i in range(n):
    sum=0.0
    for j in range(i):
      sum+=L[i,j]*x[j]
    x[i]=(b[i]-sum)/L[i,i]

  return x

In [3]:
def SustAtras(U,y):
  x=np.zeros_like(y)
  n=U.shape[0]# cantidad de renglones de U
  x[n-1]=y[n-1]/U[n-1][n-1]

  for i in range(n-2,-1,-1):
    sum=0.0
    for j in range(i+1,n):
      sum+=U[i,j]*x[j]
    x[i]=(y[i]-sum)/U[i,i]

  return x

In [4]:
def SolverLU(A,b):
  L,U=FactLU(A)
  y=SustDelante(L,b)
  x=SustAtras(U,y)

  return x

19) Dados $A$ y $b$ como sigue, resolver con factorización LU, factorización LU con pivoteo parcial y factorización LU con pivoteo total

# Factorización LU

$$
A = \begin{bmatrix}
  4 & -1 & 3 \\
  -8 & 4 & -7 \\
  12 & 1 & 8 \\
\end{bmatrix},
b =\begin{bmatrix}
  -8\\
  19\\
  -19\\
\end{bmatrix}
$$

In [7]:
A = np.array([[4, -1, 3], [-8, 4, -7], [12, 1, 8]])
b = np.array([-8, 19, -19])
print(A)
print(b)

[[ 4 -1  3]
 [-8  4 -7]
 [12  1  8]]
[ -8  19 -19]


In [9]:
SolverLU(A, b)

array([-1,  1, -1])

La solución es el vector $(-1, 1, -1)$

$$
A = \begin{bmatrix}
  1 & 4 & -2 & 1 \\
  -2 & -4 & -3 & 1 \\
  1 & 16 & -17 & 9 \\
  2 & 4 & -9 & -3
\end{bmatrix},
b =\begin{bmatrix}
  3.5\\
  -2.5\\
  15\\
  10.5
\end{bmatrix}
$$

In [10]:
A = np.array([[1, 4, -2, 1], [-2, -4, -3, 1], [1, 16, -17, 9], [2, 4, -9, -3]])
b = np.array([3.5, -2.5, 15, 10.5])
print(A)
print(b)

[[  1   4  -2   1]
 [ -2  -4  -3   1]
 [  1  16 -17   9]
 [  2   4  -9  -3]]
[ 3.5 -2.5 15.  10.5]


In [11]:
SolverLU(A, b)

array([-0.5,  1. , -0.5, -1. ])

La solución es el vector $(-0.5, 1, -0.5, -1)$

$$
A = \begin{bmatrix}
  4 & 5 & -1 & 2 & 3 \\
  12 & 13 & 0 & 10 & 3 \\
  -8 & -8 & 5 & -11 & 4 \\
  16 & 18 & -7 & 20 & 4 \\
  -4 & -9 & 31 & -31 & -1
\end{bmatrix},
b =\begin{bmatrix}
  34\\
  93\\
  -33\\
  131\\
  -58
\end{bmatrix}
$$

In [12]:
A = np.array([[4, 5, -1, 2, 3], [12, 13, 0, 10, 3], [-8, -8, 5, -11, 4], [16, 18, -7, 20, 4], [-4, -9, 31, -31, -1]])
b = np.array([34, 93, -33, 131, -58])
print(A)
print(b)

[[  4   5  -1   2   3]
 [ 12  13   0  10   3]
 [ -8  -8   5 -11   4]
 [ 16  18  -7  20   4]
 [ -4  -9  31 -31  -1]]
[ 34  93 -33 131 -58]


In [13]:
SolverLU(A, b)

array([1, 2, 3, 4, 5])

Curiosamente, la solución al sistema es el vector $(1, 2, 3, 4, 5)$